### ISSUE TITLE
arson has no --flags

### ISSUE THREAD

**Issue by Daenyth** [nogweii/arson#2]
`arson --help` causes it to download the last package (sorted). `arson -h` makes it display every(?) aur package. Can we have the old flags back please?

**Comment by nogweii** [comment]
This is a design choice by me for arson 2.0. Is it really wanted? I haven't heard of any other issues, though not many people have been vocal...

If there is serious concern/reason, I'll add them again.

**Comment by Daenyth** [comment]
I just think it makes sense to stick with the standards, especially at least with --help

**Comment by randymorris** [comment]
I'd have to agree with Daenyth.  No real reason to leave them out.  IMO they are nice to have for aliases because they are more descriptive when you look at them later.

**Comment by Daenyth** [comment]
It would also be fine to have a default of "download" if no flag is passed.

**Comment by nogweii** [comment]
heh, alright. The primary/default will still be searching - download only if passed a flag (-d? -D, as before?) and download dependencies as well, only with a flag (unlike before, which downloaded them regardless of a user's wishes). This will be activated by repeating the download flag (e.g. -d => download just the package, -dd => download the package, and it's dependencies)

I'll leave this bug open for further discussion.

**Comment by randymorris** [comment]
I like this idea. +1 from me.

**Comment by Daenyth** [comment]
Sounds good

**Comment by nogweii** [comment]
Alright, given that we are all in agreement, this is now closed. Open up a new bug report for any other issues.
