### ISSUE TITLE
Config file should go in $XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by its-danny** [nogweii/arson#8]
~/.arson.yaml should be in $XDG_CONFIG_HOME, which is usually (and by default), the $HOME/.config directory.

So, ~/.arson.yaml should become ~/.config/arson.yaml (or ~/.config/arson/arson.yaml).

Edit: Forgot to mention. $XDG_CONFIG_HOME is the freedesktop.org standard for config files.
http://standards.freedesktop.org/basedir-spec/basedir-spec-0.6.html

**Comment by nogweii** [comment]
heh, I thought about that. I would only do it if I used the ruby-xdg gem.

Although, a quick XOR could do this is as well...

Go ahead and fork if you want. :)
